server:
  port: 10999
  
logging:
  level:
    root: INFO
    info.jsjackson.services: DEBUG
    info.jsjackson.api.v1.mapper: DEBUG
    
info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@ 
    
    
#prettify the json output
spring:
  jackson:
    serialization:
      indent-output: true